version: '3.7'

services:
  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend
  server:
    build:
      context: ./
      target: development-build-stage
      dockerfile: Dockerfile
    container_name: server
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - /app/node_modules
    env_file:
      - ./.env
    restart: 'unless-stopped'
    networks:
      - backend
    depends_on:
      - emulator
  emulator:
    image: budtmo/docker-android-x86-11.0
    container_name: emulator
    privileged: true
    environment:
      - DEVICE=Samsung Galaxy S6
      - EMULATOR_PARAMS=-no-audio
    ports:
      - '6080:6080'
      - '5554:5554'
      - '5555:5555'
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
